[package]
name = "stacks-clarity"
version = "1.0.0"
edition = { workspace = true }
rust-version = { workspace = true }

[dependencies]
rand = { workspace = true }
serde = { workspace = true }
regex = "1.11.0"
lazy_static = "1.5.0"
sha2 = "0.10.8"

[lints]
workspace = true
