[package]
name = "stacks-clarity"
version = "1.0.0"
edition = { workspace = true }
rust-version = { workspace = true }

[dependencies]
getrandom = { version = "0.2", default-features = false, features = ["custom"] }
hashbrown = { version = "0.15.0", features = ["serde"] }
lazy_static = "1.5.0"
rand = { workspace = true }
regex = "1.11.0"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha2 = "0.10.8"
slog = "2.7.0"

[lints]
workspace = true
